version: '2'

services:
  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
    environment:
      - FTLCONF_LOCAL_IPV4=10.2.0.100
      - WEBPASSWORD=${WEBPASSORD}
      - PIHOLE_DNS_=10.2.0.200
      - TZ=America/Sao_Paulo
      - DNSSEC=false
      - CUSTOM_CACHE_SIZE=0
      - TEMPERATUREUNIT=c
    volumes:
      - './pihole_files/etc-pihole:/etc/pihole'
      - './pihole_files/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.100
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    # volumes:
    #   - "./unbound:/opt/unbound/etc/unbound"
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.200
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - TZ=America/Sao_Paulo
      - SUBDOMAINS=${SUBDOMAIN}
      - TOKEN=${DUCKTOKEN}
      - LOG_FILE=true
    volumes:
      - ./duck_files/:/config #optional
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.300
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '8080:80'
    volumes:
    - ./apache_website:/usr/local/apache2/htdocs

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
